### ISSUE TITLE
Support / Donation for custom apps

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple-custom#58] opened 2024-03-23 00:31 UTC
Based on the changes here: https://github.com/kiwix/apple/issues/660
We need to decide what level of customisation we would like to use.
So far it has been stated, that a single URL will be used per app (no need to localise the URL itself).
We could "customise" the URL per app, moving it into the config, and possibly we could customise the text, which can / should be localised, maybe using an additional param, something like: "Support {appName}".
We can also think about if this should be mandatory or optional, eg. leaving it out from the custom app config would either:
- not display the link at all
- fall back to the default Kiwix one

**Comment by kelson42** [comment] 2024-03-23 11:48
This an exact duplicate of https://github.com/kiwix/apple/issues/660, see [my comment ](https://github.com/kiwix/apple/issues/660#issuecomment-1964825890).

@BPerlakiH AFAIK your questions have all been answered already weeks ago... Closing.

**Closed by kelson42** 2024-03-23 11:48 UTC
Labels: enhancement
